version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: vlab_redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-123456}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    
volumes:
  redis_data: